<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Modules\FeedManagement\Models\FeedType;

class FeedTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $feedTypes = [
            [
                'name' => 'Broiler Starter Feed',
                'code' => 'BSF001',
                'description' => 'High-protein feed for broiler chicks 0-3 weeks old',
                'category' => 'starter',
                'protein_content' => 22.00,
                'energy_content' => 2900.00,
                'calcium_content' => 1.00,
                'phosphorus_content' => 0.70,
                'fiber_content' => 4.00,
                'fat_content' => 3.50,
                'cost_per_kg' => 65.00,
                'currency' => 'KES',
                'target_breed' => 'Broiler',
                'target_age_start' => 1,
                'target_age_end' => 21,
                'usage_instructions' => 'Feed ad libitum. Ensure fresh water is always available.',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Broiler Grower Feed',
                'code' => 'BGF001',
                'description' => 'Balanced nutrition for growing broilers 3-6 weeks',
                'category' => 'grower',
                'protein_content' => 19.00,
                'energy_content' => 3000.00,
                'calcium_content' => 0.90,
                'phosphorus_content' => 0.65,
                'fiber_content' => 4.50,
                'fat_content' => 4.00,
                'cost_per_kg' => 62.00,
                'currency' => 'KES',
                'target_breed' => 'Broiler',
                'target_age_start' => 22,
                'target_age_end' => 42,
                'usage_instructions' => 'Feed ad libitum with controlled lighting program',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Broiler Finisher Feed',
                'code' => 'BFF001',
                'description' => 'Final stage feed for broilers 6+ weeks',
                'category' => 'finisher',
                'protein_content' => 17.00,
                'energy_content' => 3100.00,
                'calcium_content' => 0.85,
                'phosphorus_content' => 0.60,
                'fiber_content' => 5.00,
                'fat_content' => 4.50,
                'cost_per_kg' => 60.00,
                'currency' => 'KES',
                'target_breed' => 'Broiler',
                'target_age_start' => 43,
                'target_age_end' => 56,
                'usage_instructions' => 'Feed ad libitum until market weight',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Layer Starter/Grower',
                'code' => 'LSG001',
                'description' => 'Feed for young laying hens 0-16 weeks',
                'category' => 'starter',
                'protein_content' => 18.50,
                'energy_content' => 2800.00,
                'calcium_content' => 1.20,
                'phosphorus_content' => 0.75,
                'fiber_content' => 6.00,
                'fat_content' => 3.00,
                'cost_per_kg' => 58.00,
                'currency' => 'KES',
                'target_breed' => 'Layer',
                'target_age_start' => 1,
                'target_age_end' => 112,
                'usage_instructions' => 'Feed ad libitum during development phase',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Layer Production Feed',
                'code' => 'LPF001',
                'description' => 'Feed for laying hens in production 16+ weeks',
                'category' => 'layer',
                'protein_content' => 16.50,
                'energy_content' => 2750.00,
                'calcium_content' => 3.80,
                'phosphorus_content' => 0.65,
                'fiber_content' => 6.50,
                'fat_content' => 2.80,
                'cost_per_kg' => 55.00,
                'currency' => 'KES',
                'target_breed' => 'Layer',
                'target_age_start' => 113,
                'target_age_end' => 520,
                'usage_instructions' => 'Feed 110-120g per bird per day during production',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Breeder Feed',
                'code' => 'BRF001',
                'description' => 'Specialized feed for breeding stock',
                'category' => 'breeder',
                'protein_content' => 16.00,
                'energy_content' => 2700.00,
                'calcium_content' => 3.50,
                'phosphorus_content' => 0.70,
                'fiber_content' => 7.00,
                'fat_content' => 3.20,
                'cost_per_kg' => 68.00,
                'currency' => 'KES',
                'target_breed' => 'Breeder',
                'target_age_start' => 140,
                'target_age_end' => 450,
                'usage_instructions' => 'Feed restricted amount based on age and production',
                'shelf_life_days' => 90,
                'storage_requirements' => 'Store in cool, dry place away from direct sunlight',
                'status' => 'active',
                'is_organic' => false,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Organic Starter Feed',
                'code' => 'OSF001',
                'description' => 'Organic feed for chicks with no chemicals or GMOs',
                'category' => 'starter',
                'protein_content' => 20.00,
                'energy_content' => 2850.00,
                'calcium_content' => 1.10,
                'phosphorus_content' => 0.68,
                'fiber_content' => 5.00,
                'fat_content' => 3.80,
                'cost_per_kg' => 85.00,
                'currency' => 'KES',
                'target_breed' => 'All',
                'target_age_start' => 1,
                'target_age_end' => 28,
                'usage_instructions' => 'Feed ad libitum. Certified organic ingredients only',
                'shelf_life_days' => 75,
                'storage_requirements' => 'Store in cool, dry place. Avoid contamination with non-organic feeds',
                'status' => 'active',
                'is_organic' => true,
                'is_medicated' => false,
                'created_by' => 1,
            ],
            [
                'name' => 'Medicated Chick Starter',
                'code' => 'MCS001',
                'description' => 'Medicated starter feed for disease prevention in chicks',
                'category' => 'specialist',
                'protein_content' => 21.00,
                'energy_content' => 2900.00,
                'calcium_content' => 1.00,
                'phosphorus_content' => 0.70,
                'fiber_content' => 4.00,
                'fat_content' => 3.50,
                'cost_per_kg' => 75.00,
                'currency' => 'KES',
                'target_breed' => 'All',
                'target_age_start' => 1,
                'target_age_end' => 21,
                'usage_instructions' => 'Feed only under veterinary supervision. Withdraw before slaughter',
                'shelf_life_days' => 60,
                'storage_requirements' => 'Store in cool, dry place. Keep away from other feeds',
                'status' => 'active',
                'requires_prescription' => true,
                'is_organic' => false,
                'is_medicated' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($feedTypes as $feedType) {
            FeedType::updateOrCreate(
                ['code' => $feedType['code']],
                $feedType
            );
        }
    }
}
