<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Modules\FeedManagement\Models\FeedSupplier;

class FeedSuppliersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Unga Group Limited',
                'code' => 'UNG001',
                'description' => 'Leading animal feed manufacturer in East Africa with over 90 years of experience',
                'contact_person' => 'Joseph Kiprotich',
                'email' => 'sales@unga.co.ke',
                'phone' => '+254 20 3540000',
                'website' => 'https://www.unga.co.ke',
                'address' => 'Unga House, Muthithi Road',
                'city' => 'Nairobi',
                'state' => 'Nairobi County',
                'country' => 'Kenya',
                'postal_code' => '00100',
                'tax_id' => 'P051234567M',
                'supplier_type' => 'manufacturer',
                'certifications' => ['ISO 9001:2015', 'HACCP', 'KEBS'],
                'quality_rating' => 4.5,
                'delivery_rating' => 4.2,
                'price_competitiveness' => 3.8,
                'total_orders' => 150,
                'average_delivery_days' => 2.5,
                'payment_terms_days' => 30,
                'minimum_order_value' => 50000.00,
                'delivery_areas' => ['Nairobi', 'Central Kenya', 'Rift Valley', 'Western Kenya'],
                'status' => 'active',
                'is_preferred' => true,
                'priority_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Pembe Flour Mills',
                'code' => 'PEM001',
                'description' => 'Quality feed manufacturer focused on poultry nutrition',
                'contact_person' => 'Mary Wanjiku',
                'email' => 'orders@pembeflour.co.ke',
                'phone' => '+254 722 456789',
                'website' => 'https://www.pembeflour.co.ke',
                'address' => 'Industrial Area, Enterprise Road',
                'city' => 'Nairobi',
                'state' => 'Nairobi County',
                'country' => 'Kenya',
                'postal_code' => '00100',
                'tax_id' => 'P051234568N',
                'supplier_type' => 'manufacturer',
                'certifications' => ['KEBS', 'HACCP'],
                'quality_rating' => 4.2,
                'delivery_rating' => 4.0,
                'price_competitiveness' => 4.1,
                'total_orders' => 98,
                'average_delivery_days' => 3.0,
                'payment_terms_days' => 21,
                'minimum_order_value' => 25000.00,
                'delivery_areas' => ['Nairobi', 'Central Kenya', 'Eastern Kenya'],
                'status' => 'active',
                'is_preferred' => false,
                'priority_order' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Rift Valley Feeds',
                'code' => 'RVF001',
                'description' => 'Regional feed supplier serving Rift Valley farmers',
                'contact_person' => 'Peter Kipkoech',
                'email' => 'info@riftvalleyfeeds.co.ke',
                'phone' => '+254 733 123456',
                'address' => 'Nakuru Industrial Area',
                'city' => 'Nakuru',
                'state' => 'Nakuru County',
                'country' => 'Kenya',
                'postal_code' => '20100',
                'tax_id' => 'P051234569O',
                'supplier_type' => 'distributor',
                'certifications' => ['KEBS'],
                'quality_rating' => 3.9,
                'delivery_rating' => 4.3,
                'price_competitiveness' => 4.4,
                'total_orders' => 67,
                'average_delivery_days' => 1.5,
                'payment_terms_days' => 14,
                'minimum_order_value' => 15000.00,
                'delivery_areas' => ['Rift Valley', 'Western Kenya'],
                'status' => 'active',
                'is_preferred' => false,
                'priority_order' => 3,
                'created_by' => 1,
            ],
            [
                'name' => 'Farmers Choice Feed Division',
                'code' => 'FCF001',
                'description' => 'Feed division of Farmers Choice Group specializing in poultry feeds',
                'contact_person' => 'Grace Muthoni',
                'email' => 'feeds@farmerschoice.co.ke',
                'phone' => '+254 700 123456',
                'website' => 'https://www.farmerschoice.co.ke',
                'address' => 'Thika Road, Ruiru',
                'city' => 'Ruiru',
                'state' => 'Kiambu County',
                'country' => 'Kenya',
                'postal_code' => '00232',
                'tax_id' => 'P051234570P',
                'supplier_type' => 'manufacturer',
                'certifications' => ['ISO 22000', 'KEBS', 'HACCP'],
                'quality_rating' => 4.4,
                'delivery_rating' => 4.1,
                'price_competitiveness' => 3.7,
                'total_orders' => 89,
                'average_delivery_days' => 2.8,
                'payment_terms_days' => 30,
                'minimum_order_value' => 40000.00,
                'delivery_areas' => ['Central Kenya', 'Nairobi', 'Eastern Kenya'],
                'status' => 'active',
                'is_preferred' => true,
                'priority_order' => 2,
                'created_by' => 1,
            ],
            [
                'name' => 'Coast Feed Suppliers',
                'code' => 'CFS001',
                'description' => 'Coastal region feed distributor serving Mombasa and surrounding areas',
                'contact_person' => 'Ahmed Hassan',
                'email' => 'sales@coastfeed.co.ke',
                'phone' => '+254 714 987654',
                'address' => 'Changamwe Industrial Area',
                'city' => 'Mombasa',
                'state' => 'Mombasa County',
                'country' => 'Kenya',
                'postal_code' => '80100',
                'tax_id' => 'P051234571Q',
                'supplier_type' => 'distributor',
                'certifications' => ['KEBS'],
                'quality_rating' => 3.8,
                'delivery_rating' => 3.9,
                'price_competitiveness' => 4.2,
                'total_orders' => 45,
                'average_delivery_days' => 4.0,
                'payment_terms_days' => 21,
                'minimum_order_value' => 20000.00,
                'delivery_areas' => ['Coast Province', 'Kilifi', 'Kwale'],
                'status' => 'active',
                'is_preferred' => false,
                'priority_order' => 4,
                'created_by' => 1,
            ],
            [
                'name' => 'Nyanza Poultry Feeds',
                'code' => 'NPF001',
                'description' => 'Regional feed cooperative serving Lake Victoria region',
                'contact_person' => 'John Ochieng',
                'email' => 'orders@nyanzafeeds.co.ke',
                'phone' => '+254 727 345678',
                'address' => 'Kisumu Industrial Area',
                'city' => 'Kisumu',
                'state' => 'Kisumu County',
                'country' => 'Kenya',
                'postal_code' => '40100',
                'tax_id' => 'P051234572R',
                'supplier_type' => 'cooperative',
                'certifications' => ['KEBS'],
                'quality_rating' => 3.7,
                'delivery_rating' => 4.0,
                'price_competitiveness' => 4.5,
                'total_orders' => 38,
                'average_delivery_days' => 3.5,
                'payment_terms_days' => 14,
                'minimum_order_value' => 10000.00,
                'delivery_areas' => ['Nyanza Province', 'Western Kenya'],
                'status' => 'active',
                'is_preferred' => false,
                'emergency_supplier' => true,
                'priority_order' => 5,
                'created_by' => 1,
            ],
        ];

        foreach ($suppliers as $supplierData) {
            FeedSupplier::updateOrCreate(
                ['code' => $supplierData['code']],
                $supplierData
            );
        }
    }
}
