<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\BatchIncubator\Models\MedicationProtocol;
use App\Models\User;

class MedicationProtocolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@poultriinnox.com')->first();
        if (!$adminUser) {
            $adminUser = User::factory()->create([
                'name' => 'Admin User',
                'email' => 'admin@poultriinnox.com',
                'password' => bcrypt('password'),
            ]);
        }

        $medications = [
            // Antibiotics
            [
                'name' => 'Amoxicillin Treatment Protocol',
                'medication_name' => 'Amoxicillin',
                'medication_type' => 'antibiotic',
                'description' => 'Broad-spectrum antibiotic for treating bacterial infections in poultry',
                'target_breeds' => ['Broiler', 'Layer', 'Bantam'],
                'bird_type' => 'chicken',
                'purpose' => 'broiler',
                'min_age_days' => 7,
                'max_age_days' => 365,
                'active_ingredient' => 'Amoxicillin trihydrate',
                'dosage_per_kg_body_weight' => 15.0,
                'dosage_unit' => 'mg',
                'administration_method' => 'water',
                'treatment_duration_days' => 5,
                'application_schedule' => [
                    'schedule_type' => 'event_based',
                    'triggers' => ['respiratory_infection', 'e_coli_outbreak']
                ],
                'withdrawal_period_days' => 7,
                'contraindications' => ['known_penicillin_allergy', 'egg_production'],
                'precautions' => 'Monitor birds for allergic reactions',
                'side_effects' => 'Possible digestive upset, reduced appetite',
                'cost_per_unit' => 2.50,
                'supplier' => 'Zoetis',
                'usage_count' => 25,
                'success_rate' => 92.5,
                'effectiveness_data' => [
                    'respiratory_infections' => 95,
                    'e_coli' => 88,
                    'general_bacterial' => 90
                ],
                'status' => 'active',
                'requires_prescription' => false,
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Enrofloxacin Emergency Protocol',
                'medication_name' => 'Enrofloxacin',
                'medication_type' => 'antibiotic',
                'target_disease' => 'Severe respiratory infections, Colibacillosis',
                'target_breeds' => ['Broiler', 'Layer'],
                'age_range_start' => 14,
                'age_range_end' => 365,
                'dosage_per_kg' => 10.0,
                'dosage_unit' => 'mg',
                'application_method' => 'injection',
                'treatment_duration_days' => 3,
                'withdrawal_period_days' => 14,
                'cost_per_unit' => 8.75,
                'manufacturer' => 'Bayer',
                'is_emergency_protocol' => true,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Fluoroquinolone antibiotic for severe bacterial infections',
                'instructions' => 'Administer subcutaneously. Monitor birds closely during treatment.',
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Tylosin Water Treatment',
                'medication_name' => 'Tylosin',
                'medication_type' => 'antibiotic',
                'target_disease' => 'Chronic respiratory disease, Mycoplasmosis',
                'target_breeds' => ['Layer', 'Breeder'],
                'age_range_start' => 21,
                'age_range_end' => 365,
                'dosage_per_kg' => 25.0,
                'dosage_unit' => 'mg',
                'application_method' => 'water',
                'treatment_duration_days' => 7,
                'withdrawal_period_days' => 5,
                'cost_per_unit' => 3.20,
                'manufacturer' => 'Elanco',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Macrolide antibiotic effective against Mycoplasma infections',
                'instructions' => 'Mix thoroughly in drinking water. Use fresh solution daily.',
                'created_by' => $adminUser->id,
            ],

            // Vitamins & Supplements
            [
                'name' => 'Vitamin E & Selenium Supplement',
                'medication_name' => 'Vitamin E + Selenium',
                'medication_type' => 'vitamin',
                'target_disease' => 'Nutritional deficiency, White muscle disease',
                'target_breeds' => ['Broiler', 'Layer', 'Duck'],
                'age_range_start' => 1,
                'age_range_end' => 365,
                'dosage_per_kg' => 0.5,
                'dosage_unit' => 'ml',
                'application_method' => 'injection',
                'treatment_duration_days' => 1,
                'withdrawal_period_days' => 0,
                'cost_per_unit' => 1.50,
                'manufacturer' => 'Virbac',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Essential vitamin and mineral supplement for optimal health',
                'instructions' => 'Single intramuscular injection. Repeat as needed based on condition.',
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Vitamin B Complex Water Soluble',
                'medication_name' => 'B-Complex Vitamins',
                'medication_type' => 'vitamin',
                'target_disease' => 'Stress, Poor growth, Vitamin B deficiency',
                'target_breeds' => ['Broiler', 'Layer', 'Turkey'],
                'age_range_start' => 1,
                'age_range_end' => 365,
                'dosage_per_kg' => 2.0,
                'dosage_unit' => 'g',
                'application_method' => 'water',
                'treatment_duration_days' => 5,
                'withdrawal_period_days' => 0,
                'cost_per_unit' => 0.75,
                'manufacturer' => 'Norbrook',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Water-soluble vitamin complex for stress recovery and growth',
                'instructions' => 'Dissolve in drinking water. Use during stressful periods or after antibiotic treatment.',
                'created_by' => $adminUser->id,
            ],

            // Dewormers
            [
                'name' => 'Fenbendazole Deworming Protocol',
                'medication_name' => 'Fenbendazole',
                'medication_type' => 'dewormer',
                'target_disease' => 'Roundworms, Cecal worms, Gapeworms',
                'target_breeds' => ['Layer', 'Breeder', 'Free-range'],
                'age_range_start' => 28,
                'age_range_end' => 365,
                'dosage_per_kg' => 5.0,
                'dosage_unit' => 'mg',
                'application_method' => 'feed',
                'treatment_duration_days' => 5,
                'withdrawal_period_days' => 14,
                'cost_per_unit' => 1.25,
                'manufacturer' => 'Merck',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Broad-spectrum anthelmintic for internal parasite control',
                'instructions' => 'Mix thoroughly with feed. Ensure all birds consume medicated feed.',
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Levamisole Emergency Deworming',
                'medication_name' => 'Levamisole HCl',
                'medication_type' => 'dewormer',
                'target_disease' => 'Heavy worm infestation, Ascaridia',
                'target_breeds' => ['Layer', 'Broiler', 'Turkey'],
                'age_range_start' => 21,
                'age_range_end' => 365,
                'dosage_per_kg' => 20.0,
                'dosage_unit' => 'mg',
                'application_method' => 'water',
                'treatment_duration_days' => 2,
                'withdrawal_period_days' => 7,
                'cost_per_unit' => 4.50,
                'manufacturer' => 'Janssen',
                'is_emergency_protocol' => true,
                'auto_recommend' => false,
                'status' => 'active',
                'description' => 'Fast-acting anthelmintic for severe worm infestations',
                'instructions' => 'Dissolve in drinking water. Withhold food for 12 hours before treatment.',
                'created_by' => $adminUser->id,
            ],

            // Other medications
            [
                'name' => 'Electrolyte Solution',
                'medication_name' => 'Electrolyte + Glucose',
                'medication_type' => 'supplement',
                'target_disease' => 'Dehydration, Heat stress, Transport stress',
                'target_breeds' => ['Broiler', 'Layer', 'Duck', 'Turkey'],
                'age_range_start' => 1,
                'age_range_end' => 365,
                'dosage_per_kg' => 1.0,
                'dosage_unit' => 'g',
                'application_method' => 'water',
                'treatment_duration_days' => 3,
                'withdrawal_period_days' => 0,
                'cost_per_unit' => 0.50,
                'manufacturer' => 'Vetoquinol',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Oral rehydration solution for stress and dehydration',
                'instructions' => 'Dissolve in drinking water. Use during hot weather or stressful conditions.',
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Probiotics Growth Promoter',
                'medication_name' => 'Multi-strain Probiotics',
                'medication_type' => 'supplement',
                'target_disease' => 'Digestive disorders, Poor feed conversion',
                'target_breeds' => ['Broiler', 'Layer'],
                'age_range_start' => 1,
                'age_range_end' => 365,
                'dosage_per_kg' => 0.5,
                'dosage_unit' => 'g',
                'application_method' => 'feed',
                'treatment_duration_days' => 30,
                'withdrawal_period_days' => 0,
                'cost_per_unit' => 2.75,
                'manufacturer' => 'Chr. Hansen',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Beneficial bacteria supplement for gut health and performance',
                'instructions' => 'Mix with feed daily. Store in cool, dry place.',
                'created_by' => $adminUser->id,
            ],
            [
                'name' => 'Coccidiostat Prevention',
                'medication_name' => 'Amprolium',
                'medication_type' => 'other',
                'target_disease' => 'Coccidiosis prevention',
                'target_breeds' => ['Broiler', 'Pullet'],
                'age_range_start' => 7,
                'age_range_end' => 84,
                'dosage_per_kg' => 125.0,
                'dosage_unit' => 'mg',
                'application_method' => 'water',
                'treatment_duration_days' => 7,
                'withdrawal_period_days' => 0,
                'cost_per_unit' => 1.80,
                'manufacturer' => 'Huvepharma',
                'is_emergency_protocol' => false,
                'auto_recommend' => true,
                'status' => 'active',
                'description' => 'Anticoccidial for prevention and treatment of coccidiosis',
                'instructions' => 'Use in drinking water. Monitor for signs of coccidiosis during treatment.',
                'created_by' => $adminUser->id,
            ],

            // Inactive/Archived protocols for testing
            [
                'name' => 'Outdated Chloramphenicol Protocol',
                'medication_name' => 'Chloramphenicol',
                'medication_type' => 'antibiotic',
                'target_disease' => 'Various bacterial infections',
                'target_breeds' => ['Broiler', 'Layer'],
                'age_range_start' => 14,
                'age_range_end' => 365,
                'dosage_per_kg' => 30.0,
                'dosage_unit' => 'mg',
                'application_method' => 'water',
                'treatment_duration_days' => 5,
                'withdrawal_period_days' => 28,
                'cost_per_unit' => 5.00,
                'manufacturer' => 'Generic',
                'is_emergency_protocol' => false,
                'auto_recommend' => false,
                'status' => 'inactive',
                'description' => 'DISCONTINUED: No longer recommended due to residue concerns',
                'instructions' => 'Do not use - replaced by safer alternatives',
                'created_by' => $adminUser->id,
            ],
        ];

        foreach ($medications as $medication) {
            MedicationProtocol::create($medication);
        }

        $this->command->info('Created ' . count($medications) . ' medication protocols');
    }
}
